### ISSUE TITLE
Why use vmi instead of vm for hotplug volume？

### ISSUE THREAD

**Issue by haoxiaoci** [kubevirt/csi-driver#112]
**Is your feature request related to a problem? Please describe**:
when a virtualmachineinstance has been restart, because of hotplug volume is on vmi, hotplug volume disappeared, and this cause pod mount pvc failed in tenant cluster.
detail: https://github.com/kubevirt/csi-driver/issues/110

**Describe the solution you'd like**:
1. implement csi-driver ListVolumes()， use external-attacher period resync to check if a volume is on a vmi, if volume actual status didn't match the volumeattachment status，external-attacher will be force resync the volume which will call ControllerPublishVolume(), hotplug volume again.
2. use virtualmachine instead of using virtualmachineinstance.  i found issue that use vmi instead of vm(https://github.com/kubevirt/csi-driver/pull/23), Are there any concerns about not using vm?

**Describe alternatives you've considered**:

**Additional context**:

**Comment by awels** [comment]
Sorry I haven't gotten around to answering this. Been busy getting snapshot support to be stable and working. You ask good questions, and I would have to do some digging to find answers for you. Of the top of my head I would say VMs are not suitable for this since it is just a definition of what the VM should look like. The VMI is the actual state of the running VM process. So it makes sense we keep track of the hotplugged volumes in there.

**Comment by haoxiaoci** [comment]
if you check this question and confirm that use ListVolumes() to fix it,  i have implemented ListVolumes(), i can summit a pull request.

**Comment by awels** [comment]
If you have a PR, I would love to see it. I am currently pretty busy but I will definitely test the scenario when I get a chance. Will probably create an e2e test that does test that scenario as it is a pretty important one.
